Language_having = {
    "Africa": {
        "Botswana": ["English"],
        "Burundi": ["French", "English"],
        "Cameroon": ["French", "English"],
        "Chad": ["Arabic", "French"],
        "Comoros": ["Arabic", "French"],
        "Congo, Republic of the": ["French"],
        "Congo, Democratic Republic of the": ["French", "Swahili"],
        "Djibouti": ["Arabic", "French"],
        "Egypt": ["Arabic"],
        "Eritrea": ["Arabic", "English"],
        "Eswatini": ["English"],
        "Ethiopia": ["Amharic"],
        "Gabon": ["French"],
        "Gambia": ["English"],
        "Ghana": ["English"],
        "Guinea": ["French"],
        "Ivory Coast": ["French"],
        "Kenya": ["Swahili", "English"],
        "Liberia": ["English"],
        "Libya": ["Arabic"],
        "Madagascar": ["French"],
        "Malawi": ["English"],
        "Mali": ["French"],
        "Mauritania": ["Arabic"],
        "Mauritius": ["French", "English"],
        "Morocco": ["Arabic"],
        "Mozambique": ["Portuguese"],
        "Namibia": ["Afrikaans", "English"],
        "Niger": ["French"],
        "Nigeria": ["English", "Yoruba", "Hausa", "Igbo"],
        "Rwanda": ["French", "English"],
        "Senegal": ["French"],
        "Seychelles": ["French", "English"],
        "Sierra Leone": ["English"],
        "Somalia": ["Somali", "Arabic"],
        "South Africa": ["Afrikaans", "English", "Xhosa", "Zulu"],
        "South Sudan": ["English", "Arabic"],
        "Sudan": ["Arabic", "English"],
        "Tanzania": ["Swahili", "English"],
        "Togo": ["French"],
        "Tunisia": ["Arabic"],
        "Uganda": ["Swahili", "English"],
        "Zambia": ["English"],
        "Zimbabwe": ["English", "Shona"],
    },
    "Asia": {
        "Afghanistan": ["Pashto"],
        "Armenia": ["Armenian"],
        "Azerbaijan": ["Azerbaijani"],
        "Bahrain": ["Arabic"],
        "Bangladesh": ["Bengali"],
        "Bhutan": ["Dzongkha"],
        "Brunei": ["Malay"],
        "Cambodia": ["Khmer"],
        "China": ["Chinese (Simplified)"],
        "Georgia": ["Georgian"],
        "India": ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil", "Urdu", "Gujarati", "Malayalam"],
        "Indonesia": ["Indonesian"],
        "Iran": ["Persian"],
        "Iraq": ["Arabic"],
        "Israel": ["Hebrew", "Arabic"],
        "Japan": ["Japanese"],
        "Jordan": ["Arabic"],
        "Kazakhstan": ["Kazakh"],
        "Kuwait": ["Arabic"],
        "Kyrgyzstan": ["Kyrgyz"],
        "Laos": ["Lao"],
        "Lebanon": ["Arabic"],
        "Malaysia": ["Malay"],
        "Maldives": ["Dhivehi"],
        "Mongolia": ["Mongolian"],
        "Myanmar": ["Burmese"],
        "Nepal": ["Nepali"],
        "North Korea": ["Korean"],
        "Oman": ["Arabic"],
        "Pakistan": ["Urdu"],
        "Palestine": ["Arabic"],
        "Philippines": ["Tagalog (Filipino)"],
        "Qatar": ["Arabic"],
        "Saudi Arabia": ["Arabic"],
        "Singapore": ["English", "Malay"],
        "South Korea": ["Korean"],
        "Sri Lanka": ["Sinhala (Sinhalese)", "Tamil"],
        "Syria": ["Arabic"],
        "Tajikistan": ["Tajik"],
        "Thailand": ["Thai"],
        "Timor-Leste": ["Portuguese"],
        "Turkmenistan": ["Turkmen"],
        "United Arab Emirates": ["Arabic"],
        "Uzbekistan": ["Uzbek"],
        "Vietnam": ["Vietnamese"],
    },
    "Europe": {
        "Albania": ["Albanian"],
        "Andorra": ["Catalan"],
        "Austria": ["German"],
        "Belarus": ["Belarusian"],
        "Belgium": ["Dutch", "French"],
        "Bosnia and Herzegovina": ["Bosnian", "Croatian", "Serbian"],
        "Bulgaria": ["Bulgarian"],
        "Croatia": ["Croatian"],
        "Cyprus": ["Greek", "Turkish"],
        "Czech Republic": ["Czech"],
        "Denmark": ["Danish"],
        "Estonia": ["Estonian"],
        "Finland": ["Finnish"],
        "France": ["French"],
        "Germany": ["German"],
        "Greece": ["Greek"],
        "Hungary": ["Hungarian"],
        "Iceland": ["Icelandic"],
        "Ireland": ["Irish"],
        "Italy": ["Italian"],
        "Latvia": ["Latvian"],
        "Lithuania": ["Lithuanian"],
        "Luxembourg": ["French", "German"],
        "Malta": ["Maltese"],
        "Moldova": ["Romanian"],
        "Monaco": ["French"],
        "Montenegro": ["Montenegrin"],
        "Netherlands": ["Dutch"],
        "North Macedonia": ["Macedonian"],
        "Norway": ["Norwegian"],
        "Poland": ["Polish"],
        "Portugal": ["Portuguese"],
        "Romania": ["Romanian"],
        "Russia": ["Russian"],
        "San Marino": ["Italian"],
        "Serbia": ["Serbian"],
        "Slovakia": ["Slovak"],
        "Slovenia": ["Slovene"],
        "Spain": ["Spanish"],
        "Sweden": ["Swedish"],
        "Switzerland": ["German", "French", "Italian"],
        "Ukraine": ["Ukrainian"],
        "United Kingdom": ["English"],
        "Vatican City": ["Italian"],
    },
    "North America": {
        "Antigua and Barbuda": ["English"],
        "Bahamas": ["English"],
        "Barbados": ["English"],
        "Belize": ["English"],
        "Canada": ["English", "French"],
        "Costa Rica": ["Spanish"],
        "Cuba": ["Spanish"],
        "Dominica": ["English"],
        "Dominican Republic": ["Spanish"],
        "El Salvador": ["Spanish"],
        "Grenada": ["English"],
        "Guatemala": ["Spanish"],
        "Haiti": ["French"],
        "Honduras": ["Spanish"],
        "Jamaica": ["English"],
        "Mexico": ["Spanish"],
        "Nicaragua": ["Spanish"],
        "Panama": ["Spanish"],
        "Saint Kitts and Nevis": ["English"],
        "Saint Lucia": ["English"],
        "Saint Vincent and the Grenadines": ["English"],
        "United States": ["English"],
    },
    "South America": {
        "Argentina": ["Spanish"],
        "Bolivia": ["Spanish"],
        "Brazil": ["Portuguese"],
        "Chile": ["Spanish"],
        "Colombia": ["Spanish"],
        "Ecuador": ["Spanish"],
        "Guyana": ["English"],
        "Paraguay": ["Spanish"],
        "Peru": ["Spanish"],
        "Suriname": ["Dutch"],
        "Uruguay": ["Spanish"],
        "Venezuela": ["Spanish"],
    },
    "Oceania": {
        "Australia": ["English"],
        "Fiji": ["English"],
        "Kiribati": ["English"],
        "Marshall Islands": ["English"],
        "Micronesia": ["English"],
        "New Zealand": ["English"],
        "Palau": ["English"],
        "Papua New Guinea": ["English"],
        "Samoa": ["English"],
        "Solomon Islands": ["English"],
        "Tonga": ["English"],
        "Tuvalu": ["English"],
        "Vanuatu": ["English", "French"],
    },
    "Antarctica": {
        "Antarctica": ["No official language"],
    },
}
